### ISSUE TITLE
SSL error: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by suhr** [eribertomota/axel#29]
I guess, axel should prefer TLS over SSL.

**Comment by sdt** [comment]
Could you please provide some more details there @suhr ?

What command were you trying to run? What operating system are you on?

**Comment by suhr** [comment]
> What command were you trying to run?

```sh
$ axel 'https://static.rust-lang.org/dist/rust-1.10.0-x86_64-unknown-linux-gnu.tar.gz'
```

> What operating system are you on?

Gentoo. Axel version: 2.11 (custom ebuild).

SSLv3 is insecure, so a lot of sites reject it.

See also: http://stackoverflow.com/questions/26640628/sslv3-alert-handshake-failure

**Comment by suhr** [comment]
Possible solution: try to use TLS first, and if the site doesn't support it, fallback to SSL.

**Comment by sdt** [comment]
I'm going on vacation until the 8th of August, so I won't be able to look into this until then.

FWIW, I get the same error on axel 2.11 from mac homebrew.

**Comment by sdt** [comment]
This appears to be an SNI issue.

see: http://security.stackexchange.com/questions/101965/ssl3-error-when-requesting-connection-using-tls-1-2

The commit above has a _partial_ fix, but needs some more work.

**Comment by douglascamata** [comment]
Ping! 

I'm having this issue too :(

**Comment by snowdream** [comment]
i get the problem too, when i use axel with mac.
```
 axel -n 10 https://download-cf.jetbrains.com/idea
/ideaIU-2016.3.dmg
```

axel SSL error: sslv3 alert handshake failure

**Comment by Zibri** [comment]
same here

**Comment by fewtime** [comment]
I get the same problem, when I use it on Archlinux
Version: Axel version 2.12 (Linux)
OS: Archlinux
`axel https://download.jetbrains.com/idea/ideaIU-2017.1.tar.gz`

Error mesage:
`SSL error: sslv3 alert handshake failure`

**Comment by daniel12fsp** [comment]
I get the same problem, when I use it on Ubuntu 16.10
Version: Axel version 2.11 (Linux)
OS: Archlinux
axel -n 5 -a http://download.docker.com/linux/ubuntu/dists/yakkety/pool/stable/amd64/docker-ce_17.03.0\~ce-0\~ubuntu-yakkety_amd64.deb


Error mesage:
SSL error: sslv3 alert handshake failure

**Comment by xiaoxiaoleo** [comment]
@snowdream @Zibri  Change protocal  https to http :)  ,then fixed!
 axel -n 10 http://download-cf.jetbrains.com/python/pycharm-professional-2017.1.4.dmg

**Comment by snowdream** [comment]
@xiaoxiaoleo thank you. it works.

**Comment by ismaell** [comment]
Fixed by commit 896310575868ec883a30f768c32771a5bf6dc451.

**Comment by C00kiie** [comment]
This issue is still can be reproduced in version 2.2 (axel --version)

`axel --num-connections 8 --insecure https://download.jetbrains.com/idea/ideaIU-2018.3.5.tar.gz`
I also tried:
`axel --num-connections 8  https://download.jetbrains.com/idea/ideaIU-2018.3.5.tar.gz`

**Comment by ismaell** [comment]
@C00kiie 2.2 is very old, why are you using that version?
